name = "aidobe"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Default (production)
[[r2_buckets]]
binding = "R2_OUTPUTS"
bucket_name = "aidobe-outputs"

[[r2_buckets]]
binding = "R2_PROMPTS"
bucket_name = "aidobe-prompts"

[[d1_databases]]
binding = "DB"
database_name = "aidobe"
database_id = "a655c188-541c-4445-9129-b1994a5f0290"

[env.dev]
vars = { ENVIRONMENT = "dev" }

[[env.dev.r2_buckets]]
binding = "R2_OUTPUTS"
bucket_name = "aidobe-outputs"
[[env.dev.r2_buckets]]
binding = "R2_PROMPTS"
bucket_name = "aidobe-prompts"
[[env.dev.d1_databases]]
binding = "DB"
database_name = "aidobe"
database_id = "a655c188-541c-4445-9129-b1994a5f0290"

[env.prod]
vars = { ENVIRONMENT = "prod" }
[[env.prod.r2_buckets]]
binding = "R2_OUTPUTS"
bucket_name = "aidobe-outputs"
[[env.prod.r2_buckets]]
binding = "R2_PROMPTS"
bucket_name = "aidobe-prompts"
[[env.prod.d1_databases]]
binding = "DB"
database_name = "aidobe"
database_id = "a655c188-541c-4445-9129-b1994a5f0290"